### ISSUE TITLE
Rename internal parent

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#10]
add a .parent getter for context resolvement on prototype

**Comment by jimdebeer** [comment]
parent getter OR parent method

**Comment by jimdebeer** [comment]
parent getter makes it pretty similar to what we have now

**Comment by jimdebeer** [comment]
@youzi what do you think parent just a method OR a getter

**Comment by jimdebeer** [comment]
pro for parent hides difficulties, pro for a method can use it for lookup and root as well

although i really like root and parent as getters

**Comment by youzi** [comment]
I like the method idea. It's more "real"

**Comment by jimdebeer** [comment]
meh its pretty nice though the .root and .parent plp love it -- but yeah will be weird that it are the only fields that you can just use
