### ISSUE TITLE
.keys() return an empty array if there are no keys

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#144]
@youzi @mstdokumaci 

what do you think?

**Comment by jimdebeer** [comment]
to avoid `value: { $: 'collection', $transform: val => val.keys() && val.keys().length }` this kind of stuff

**Comment by mstdokumaci** [comment]
that's what i would expect actually. it's always better to keep things in same type, so our code will crash less.
like `s.keys().pop()` will not throw on no-key scenario.

**Comment by jimdebeer** [comment]
yes its fixed ;)
