### ISSUE TITLE
Add weakmap funcitonality

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#16]
since we use set and get for everything its pretty easy to add weakmap functionality, api will be like es6 Sets which is nice

**Comment by jimdebeer** [comment]
@youzi what do you think?

**Comment by youzi** [comment]
@jimdebeer Seems to me this would impact our API quite a bit — how would this work? We would add some extra methods?

**Comment by jimdebeer** [comment]
not nessecary
