### ISSUE TITLE
Key property

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#21]
do we want to be able to set `({ key: xxx' })`

**Comment by youzi** [comment]
I only use this for dev'ing / tests

**Comment by jimdebeer** [comment]
me too but still i do use it a lot 
@marcusbesjes what do you think?

**Comment by marcusbesjes** [comment]
shit didn't see this, I never set key, I do use the `obs.key` property though

**Comment by jimdebeer** [comment]
i may need to add .key then @youzi is this ok for you?
