### ISSUE TITLE
On method

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#25]
annoying since it requires the differences in keys maybe just don't add this

**Comment by youzi** [comment]
I only use on method in debugging. Does make sense to have it if you have .once and .is

**Comment by jimdebeer** [comment]
ok

**Comment by jimdebeer** [comment]
its ambiguous though -- `set { on: }` and `.on`

**Comment by jimdebeer** [comment]
dont have is anymore only .once, once cant be set

**Comment by jimdebeer** [comment]
@marcusbesjes @mstdokumaci  do you use .on ?

**Comment by mstdokumaci** [comment]
i use it often and it provides api for tools i create. but not a big deal, they all can be converted to `.set({ on: ... })`.

**Comment by jimdebeer** [comment]
no worries I can make it just wanted to be sure its actually necessary, if @marcusbesjes  uses it as well ill make it

**Comment by marcusbesjes** [comment]
Even though I see that I barely use it in "actual code", I'd still like to be able to go

``` js
obs.on('data', val => console.log('hey!', val))
```

in stead of having to

``` js
obs.set({
  on: {
    data: {
      unique () {
        console.log('hey!', val)
      }
    }
  }
})
```

bottom line: I don't use it in my resulting "actual" code, but I think I will miss it and I like it as a utility method

**Comment by jimdebeer** [comment]
ok its decided then ill make it
