### ISSUE TITLE
Origin Method Enhancements (level)

### ISSUE THREAD

**Issue by youzi** [vigour-io/brisky-struct#26]
If `.parent()` will get an argument for "level", it might make sense to have `.origin()` also have an option for "level".

There are cases where you would want to define the "max level" of origin.
```js
.origin(1) // would equal .val || itself
.origin(2) // would equal .val.val || .val || itself
// ...etc
```

Also you could prevent:
```js
x.origin().set(y) // fine
console.log(x.origin()) // max callstack!
```
by doing
```js
x.origin().set(y) // fine
console.log(x.origin(1)) // fine
```

**Comment by jimdebeer** [comment]
does not do max callstack anymore

**Comment by jimdebeer** [comment]
would prefer not to add it never saw the need ever
