### ISSUE TITLE
Off method

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#32]
do we really need this
@mstdokumaci 
@youzi 
@marcusbesjes

**Comment by mstdokumaci** [comment]
if we have auto removal of listeners on remove, i guess no need for this.

**Comment by marcusbesjes** [comment]
I've never needed it since `once` and `is`

**Comment by jimdebeer** [comment]
@youzi thoughts?

**Comment by jimdebeer** [comment]
ditched

**Comment by youzi** [comment]
No need for it
