### ISSUE TITLE
automatically execute functions used as .val when calling compute

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#35]
@youzi 
@marcusbesjes

**Comment by marcusbesjes** [comment]
Is this is when I would go

``` js
const bla = new Struct({
  herk () { console.log('lolwex') }
})
```

I dont think I ever did this

**Comment by marcusbesjes** [comment]
but yeah sounds logical to me, I just never did functions in val, only defined methods and put transforms

**Comment by jimdebeer** [comment]
yeah some for me

**Comment by jimdebeer** [comment]
but ill do it :D
