### ISSUE TITLE
Make a parser for subscriptions in .subscribe

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-struct#44]
this can parse true to val: true

**Comment by jimdebeer** [comment]
allows things like `{ $any: true }`

**Comment by jimdebeer** [comment]
@youzi @marcusbesjes what do you think?

**Comment by marcusbesjes** [comment]
I'd like to go `{ $any: true }` (subscribe to anything in here with nested) or even `{ $any: { title: true }` (subscribe to all titles in here without nested).

I know @mstdokumaci needs to subscribe to "any change in X.services" using the `subscribe` API

**Comment by jimdebeer** [comment]
ok it will be done

**Comment by jimdebeer** [comment]
also add 'property' (that gets written to 1)
or somehting else what is the word for "create" and "remove"

**Comment by jimdebeer** [comment]
use the internal function in render and hub (already gets parsed)

**Comment by youzi** [comment]
`'property'` or `'prop'`. Word for "add or remove" would be nice, is there such a word?

**Comment by jimdebeer** [comment]
apparently not :D

**Comment by jimdebeer** [comment]
property it is

**Comment by mstdokumaci** [comment]
existency?
