### ISSUE TITLE
Order of event arguments

### ISSUE THREAD

**Issue by mstdokumaci** [vigour-io/brisky-struct#59]
Previously observable was almost an EventEmitter drop-in, now the new struct is not because every event is fired with arguments: `(struct, val, stamp)`.

Let's say we have a `s = struct({something: 'something'})`

When we emit an error like `s.emit('error', 'Some terrible error')`

Listener needs to be implemented as: `s.on('error', (s, err) => {/* handling goes here*/})`.

The first argument is useless here, because we already have access to s.

This can be solved by changing order of arguments like `(val, stamp, struct)` or something.

@youzi @marcusbesjes Let's discuss about this a little bit, what's the best order of args here? What are our usecases?

**Comment by youzi** [comment]
Ideally you would get event object first. This is convention for both node and DOM events (relevant since we use these emitters in brisky-render).

**Comment by jimdebeer** [comment]
@youzi  so not the struct first but the val first?

**Comment by jimdebeer** [comment]
@marcus what do you think?

**Comment by youzi** [comment]
If we are getting these 3 args, and they are the same args that we use for evry method - we should keep the order the same, disregarding conventions. Consistency over convention

**Comment by mstdokumaci** [comment]
and if it's possible to apply convention everywhere, then we can say consistently convention :)

**Comment by marcusbesjes** [comment]
I agree with @mstdokumaci, `(val, stamp, struct)` is the most logical order to me as well.
`val` is the thing most handlers will be interested in primarily, and `struct` is not needed when you use `struct.on('event', (val, stamp, struct) => console.log('hey already have struct here!', struct)`

**Comment by jimdebeer** [comment]
ok this will be it then!
