### ISSUE TITLE
Way to exclude keys

### ISSUE THREAD

**Issue by youzi** [vigour-io/brisky-struct#8]
So we can have keys in state, which don't render in brisky render (collection)

**Comment by jimdebeer** [comment]
we can think of a more elegant solution then the filter function

**Comment by jimdebeer** [comment]
adds lots of problems for hub sync -- maybe we can just use test for now? or a custom exclusion in brisky-render

**Comment by jimdebeer** [comment]
need to find a good system for this (something like filter) but we may add this specific in brisky-render (rename of core) other solution is in the any subscription

**Comment by jimdebeer** [comment]
were checking to be able to use a filter method that gets cached

**Comment by jimdebeer** [comment]
so would become something like
.cache('ui').filter(() => )
idea is that we can cache functional stuff need to find a better way perhaps

**Comment by jimdebeer** [comment]
other api is .filter(), true)

**Comment by jimdebeer** [comment]
its going to be subscription based, in any subscription you can use all "functional" things, sort, filter, map, slice etc (basically a keys mod in your subscription)

**Comment by jimdebeer** [comment]
see #28
